---
- hosts: kube

  tasks:
  
  - name: Kubeadm reset
    shell: kubeadm reset
    become: yes

  - name: Remove .kube
    file:
      state: absent
      path: "{{ ansible_env.HOME }}/.kube"

  - name: Restart kubelet
    systemd:
      name: kubelet
      state: restarted
    become: yes

  - name: Reboot
    shell: sleep 2 && shutdown -r now
    become: yes
    async: 1
    poll: 0

#  - name: Wait for 30 seconds
#    pause: seconds=30

  - name: Wait for host to come up
#    local_action: shell ansible -u {{ ansible_user_id }} -m ping {{ inventory_hostname }}
#    register: result
#    until: result.rc == 0
#    retries: 30
#    delay: 10
    local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=10 timeout=120 
