---
- hosts: kube

  tasks:
  
  - name: Verify if kubeadm exists
    shell: which kubeadm
    register: kubeadm_result
    failed_when: false
    changed_when: false
 
  - debug: var=kubeadm_result

  - name: Kubeadm reset
    shell: kubeadm reset
    become: yes
    when: kubeadm_result.rc == 0

  - name: Remove .kube
    file:
      state: absent
      path: "{{ ansible_env.HOME }}/.kube"
 
  - name: Verify if kubelet service exists
    shell: "if systemctl status firewalld | grep -q loaded; then echo true; else echo false ; fi;"
    register: kubelet_installed
    changed_when: false

  - name: Restart kubelet
    systemd:
      name: kubelet
      state: restarted
    become: yes
    when: kubelet_installed == "true"

  - name: Reboot
    shell: sleep 2 && shutdown -r now
    become: yes
    async: 1
    poll: 0

  - name: Wait for host to come up
    local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=10

  - name: Wait for 10 seconds
    pause: seconds=10

