---
# ------------------- etcd deployment ------------------- #

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: etcd3par
  name: etcd3par
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: etcd3par
  template:
    metadata:
      labels:
        k8s-app: etcd3par
    spec:
      containers:
      - name: etcd3par
        image: quay.io/coreos/etcd:v2.2.0
        ports:
        - containerPort: 2379
          protocol: TCP
        - containerPort: 2380
          protocol: TCP
        - containerPort: 4001
          protocol: TCP
        command:
          - /etcd
          - --name
          - etcd3par
          - --initial-advertise-peer-urls
          - http://etcd3par:2380
          - --listen-peer-urls
          - http://0.0.0.0:2380
          - --listen-client-urls
          - http://0.0.0.0:2379
          - --advertise-client-urls
          - http://etcd3par:2379
          - --initial-cluster
          - etcd3par=http://etcd3par:2380
          - --initial-cluster-state
          - new
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: crt-volume
      volumes:
      - name: crt-volume
        emptyDir: {}
      # Comment the following tolerations if etcd must not be deployed on master
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

---
# ------------------- Dashboard Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: etcd3par
  name: etcd3par
  namespace: kube-system
spec:
  ports:
  - port: 2379
    targetPort: 2379 
  selector:
    k8s-app: etcd3par
  type: NodePort
