---
 - name: copy busybox deployment
   copy:
     src: ./files/busybox.yaml
     dest: /tmp/.

 - name: deploy busybox
   shell: "kubectl create -f /tmp/busybox.yaml"

 - name: Wait for busybox to be in running state
   shell: "kubectl get pods busybox | tail -n +2 | grep -v -w 'Running' || true"
   register: result
   until: result.stdout == ""
   retries: 60
   delay: 10
   changed_when: false

 - name: Check if DNS is working
   shell: "kubectl exec -ti busybox -- nslookup kubernetes.default"
   register: result
   changed_when: false

 - debug: var=result.stdout

 - name: Delete busybox deployment
   shell: "kubectl delete -f /tmp/busybox.yaml"
