---
##NB: I didnt test 'cause I did this part manually

 - name: configure yum proxy
   lineinfile:
     path: /etc/yum.conf
     regexp: '^proxy='
     line: 'proxy={{ yum_proxy }}'
   become: yes

 - name: yum clean
   shell: yum clean expire-cache
   become: yes

 - name: yum update
   yum: name=* state=latest
   become: yes   

 - name: configure ip forwarding
   template: src=./templates/sysctl.conf.j2 dest=/etc/sysctl.d/kubernetes.conf
   become: yes

 - name: disable selinux/setenforce 0
   selinux: state=disabled
   become: yes

 - name: check if firewalld is installed
   shell: "if systemctl status firewalld | grep -q loaded; then echo true; else echo false ; fi;"
   register: firewalld_installed

 - name: disable firewalld
   service: name=firewalld state=stopped enabled=no
   become: yes
   when: "firewalld_installed == true"

# - name: modprobe bridge netfilter
#   modprobe: name=br_netfilter state=present

# - name: sysctl br ntfilter and ip forwarding
#   sysctl: reload=yes sysctl_file=/etc/sysctl.d/kubernetes.conf
