---
# Installs and configure NTP
#
 - name: Install kubectl
   yum: name=kubernetes-client state=installed
   become: yes

 - name: Create .kube dir
   file: path={{ ansible_env.HOME }}/.kube state=directory

 - name: Create kubernets pki dir
   file: path=/etc/kubernetes/pki state=directory
   become: yes

 - name: Configure .kube/config
   local_action: "shell {{ item }}"
   with_items:
   - kubectl config set-cluster default-cluster --server=https://{{ inventory_hostname }}:6443 --certificate-authority=/etc/kubernetes/pki/ca.crt
   - kubectl config set-credentials default-admin --certificate-authority=/etc/kubernetes/pki/ca.crt --client-key=/etc/kubernetes/pki/kubecfg.key --client-certificate=/etc/kubernetes/pki/kubecfg.crt
   - kubectl config set-context default-context --cluster=default-cluster --user=default-admin
   - kubectl config use-context default-context
