---
# Flannel configuration for all nodes

 - name: /etc/sysconfig/flanneld FLANNEL_ETCD
   lineinfile:
     path: /etc/sysconfig/flanneld
     regexp: '^FLANNEL_ETCD_ENDPOINTS='
     line: 'FLANNEL_ETCD_ENDPOINTS="http://{{ kube_master }}:2379"'
   become: yes

 - name: /etc/sysconfig/flanneld FLANNEL_ETCD_PREFIX
   lineinfile:
     path: /etc/sysconfig/flanneld
     regexp: '^FLANNEL_ETCD_PREFIX='
     line: 'FLANNEL_ETCD_PREFIX="{{ etcd_prefix }}"'
   become: yes

 - name: Start and enable flanneld
   service: name=flanneld state=started enabled=yes
   become: yes

