hpe3par_plugin_version: 2.0.1
# Port that will be fixed for etcd service required for the docker volume plugin. Has to be a value between 30000-32767.
etcd_port: 30002
hpe3par_api_url: https://10.1.2.3:8080/api/v1
hpe3par_user: user
hpe3par_password: password
hpe3par_san_ip: 10.3.4.5
hpe3par_san_login: sanuser
hpe3par_san_password: sanpassword
hpe3par_cpg: cpg
hpe3par_iscsi_ip: 10.6.7.8
hpe3par_iscsi_ips: 10.6.7.8,10.9.10.11,10.12.13.14
