---

- name: Add hosts to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: '{{ hostvars[item].ansible_ssh_host }} {{ item }}'
    state: present
  with_items: '{{ groups["kube"] }}'
  become: yes
