---
# Master configuration


 - name: Run Kubeadm
   shell: "export https_proxy={{ proxy }} && export http_proxy={{ proxy }} && export no_proxy=127.0.0.1,localhost,{{ hostvars[groups.master[0]].ansible_ssh_host }} && kubeadm init --pod-network-cidr={{ network_cidr }}"
   become: yes

 - name: Create .kube dir
   file: 
     path: $HOME/.kube
     state: directory

 - name: Copy kubeconfig to .kube
   shell: "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"

 - name: Change owner of kubeconfig
   shell: "sudo chown $(id -u):$(id -g) $HOME/.kube/config"
