---
# get .kube/config from master
 - name: test
   debug: var=ansible_env.HOME

 - name: Get .kube/config
   fetch: src={{ ansible_env.HOME }}/.kube/config dest={{ ansible_env.HOME }}/.kube/config flat=yes

 - name: Get kuberntes kubecfg.crt
   fetch: src=/etc/kubernetes/pki/kubecfg.crt dest=/etc/kubernetes/pki/kubecfg.crt flat=yes
   become: yes

 - name: Get kuberntes kubecfg.key
   fetch: src=/etc/kubernetes/pki/kubecfg.key dest=/etc/kubernetes/pki/kubecfg.key flat=yes
   become: yes

 - name: Get kuberntes ca.crt
   fetch: src=/etc/kubernetes/pki/ca.crt dest=/etc/kubernetes/pki/ca.crt flat=yes
   become: yes
