---
# CNI network configuration

 - name: deploy Calico
   when: cni_network == "calico"
   shell: "kubectl apply -f http://docs.projectcalico.org/v2.4/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml"
   environment: '{{ proxy | default ({}) }}'

 - name: wait for Calico deployment
   when: cni_network == "calico"
   shell: "kubectl get pods --all-namespaces | grep kube-dns"
   register: result
   until: result.stdout.find("Running") != -1
   retries: 30
   delay: 10

 - name: deploy Flannel
   when: cni_network == "flannel"
   shell: "{{ item }}"
   with_items:
   - "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.8.0/Documentation/kube-flannel.yml"
   - "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.8.0/Documentation/kube-flannel-rbac.yml"
   environment: '{{ proxy | default ({}) }}'
   register: flannel
   changed_when: '"created" in flannel.stdout'

 - name: wait for Flannel deployment
   when: cni_network == "flannel"
   shell: "kubectl get pods --all-namespaces | grep kube-dns"
   register: result
   until: result.stdout.find("Running") != -1
   retries: 30
   delay: 10

 - name: deploy Weave
   when: cni_network == "weave"
   shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
   register: weave
   changed_when: '"created" in weave.stdout'

 - name: wait for Weave deployment
   when: cni_network == "weave"
   shell: "kubectl get pods --all-namespaces | grep kube-dns"
   register: result
   until: result.stdout.find("Running") != -1
   retries: 30
   delay: 10
