---
# CNI network configuration


 - name: Deploy Calico
   shell: "https_proxy={{ proxy }} kubectl apply -f http://docs.projectcalico.org/v2.4/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml"
   when: cni_network == "calico"
