---
# CNI network configuration

 - name: deploy Calico
   when: cni_network == "calico"
   shell: "kubectl apply -f {{ calico }}" 
   environment: '{{ proxy_env | default ({}) }}'

 - name: wait for Calico deployment
   when: cni_network == "calico"
   shell: "kubectl get pods --all-namespaces | grep kube-dns"
   register: result
   until: result.stdout.find("Running") != -1
   retries: "{{ timeout | default(60) }}"
   delay: 10
   changed_when: false

 - name: set net.bridge.bridge-nf-call-iptables=1
   shell: "sysctl net.bridge.bridge-nf-call-iptables=1"
   become: yes
   when: cni_network == "flannel" or cni_network == "weave"

 - name: deploy Flannel
   when: cni_network == "flannel"
   environment: '{{ proxy_env | default ({}) }}'
   shell: "kubectl apply -f {{ flannel }}" 
   register: flannel
   changed_when: '"created" in flannel.stdout'

 - name: wait for Flannel deployment
   when: cni_network == "flannel"
   shell: "kubectl get pods --all-namespaces | grep kube-dns"
   register: result
   until: result.stdout.find("Running") != -1
   retries: "{{ timeout | default(60) }}"
   delay: 10
   changed_when: false

 - name: deploy Weave
   when: cni_network == "weave"
   shell: "kubectl apply -f {{ weave }}"
   environment: '{{ proxy_env | default ({}) }}'
   register: weave
   changed_when: '"created" in weave.stdout'

 - name: wait for Weave deployment
   when: cni_network == "weave"
   shell: "kubectl get pods --all-namespaces | grep kube-dns"
   register: result
   until: result.stdout.find("Running") != -1
   retries: "{{ timeout | default(60) }}"
   delay: 10
   changed_when: false

 - name: Wait for 10 seconds
   pause: seconds=10
