---
# CNI network configuration

 - name: copy calico yaml
   when: cni_network == "calico"
   copy: src=./files/calico.yaml dest=/tmp/calico.yaml

 - name: deploy calico template
   when: cni_network == "calico"
   shell: "kubectl apply -f /tmp/calico.yaml"

 - name: wait for Calico deployment
   when: cni_network == "calico"
   shell: "kubectl get pods --all-namespaces | grep etcd"
   register: result
   until: result.stdout.find("Running") != -1
   retries: 30
   delay: 10
