---
# Install Kubernetes, Docker and ETCD from repo

 - name: Setup yum repo
   yum_repository:
     name: virt7-docker-common-release
     description: containers repo
     baseurl: http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/
     gpgcheck: no
   become: yes

 - name: Install kubernetes package
   yum: name=kubernetes state=installed enablerepo=virt7-docker-common-release
   become: yes

 - name: Install docker package
   yum: name=docker state=installed enablerepo=virt7-docker-common-release
   become: yes

 - name: Install etcd package
   yum: name=etcd state=installed enablerepo=virt7-docker-common-release
   become: yes

 - name: Install flannel package
   yum: name=flannel state=installed enablerepo=virt7-docker-common-release
   become: yes

