---
# Installs and configure docker
#

- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest
  become: yes

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest
  become: yes

- name: Install lvm2
  yum:
    name: lvm2
    state: latest
  become: yes

- name: Add docker repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: yes

- name: Install docker
  yum:
    name: docker-ce 
    state: latest
  become: yes

- name: create systemd docker.service
  file: path=/etc/systemd/system/docker.service.d state=directory
  become: yes

- name: Add proxy to docker
  template: src=./templates/http-proxy.conf.j2 dest=/etc/systemd/system/docker.service.d/http-proxy.conf
  become: yes
  when: proxy is defined


- name: Systemctl reload
  command: "systemctl daemon-reload"
  become: yes

- name: Start and enable docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
  become: yes
