apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: 2017-09-05T14:03:02Z
    name: php-apache
    namespace: default
    resourceVersion: "573428"
    selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/php-apache
    uid: ee99c1a0-9242-11e7-9a92-fa163e6c5fea
  spec:
    maxReplicas: 10
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: php-apache
    targetCPUUtilizationPercentage: 50
  status:
    currentCPUUtilizationPercentage: 0
    currentReplicas: 1
    desiredReplicas: 1
    lastScaleTime: 2017-09-05T14:27:05Z
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
