---


- name: 3par plugin - Install plugin OS dependencies
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - iscsi-initiator-utils
    - device-mapper-multipath
  environment: '{{ proxy_env | default ({}) }}'
  become: yes


- name: 3par plugin - Reload systemd
  command: systemctl daemon-reload
  become: yes

- name: 3par plugin - Enable services
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - iscsid
    - multipathd
  become: yes


- name: 3par plugin - services
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - iscsid
    - multipathd
  become: yes

