- name: 3par plugin - Create 3par plugin directory
  file:
    path: /etc/hpedockerplugin
    state: directory
  become: yes

- name: 3par plugin - Set 3par IP
  set_fact:
    etcd_ip: "{{ hostvars[inventory_hostname].ansible_ssh_host }}"

- name: 3par plugin - Copy 3par plugin configuration
  template:
    src: ././templates/3parplugin.conf
    dest: /etc/hpedockerplugin/hpe.conf
  become: yes

- include: roles/addons/tasks/3parplugin_install_debian_dependencies.yml
  when: ansible_os_family == "Debian" 

- include: roles/addons/tasks/3parplugin_install_redhat_dependencies.yml
  when: ansible_os_family == "RedHat"

- name: 3par plugin - check if installed and version
  shell: "sudo docker plugin inspect hpe | grep PluginReference | cut -d':' -f 3 | tr -d ',' | tr -d '\"'"
  register: installed_version
  changed_when: false

- name: 3par plugin - Install docker plugin
  shell: "docker plugin install store/hpestorage/hpedockervolumeplugin:{{ hpe3par_plugin_version }} --alias hpe --disable --grant-all-permissions"
  become: yes
  when: hpe3par_plugin_version != installed_version.stdout

- name: 3par plugin - set certs.source dir
  shell: docker plugin set hpe certs.source=/tmp
  become: yes
  when: hpe3par_plugin_version != installed_version.stdout
 
- name: 3par plugin - set glibc_libs.source dir
  shell: docker plugin set hpe glibc_libs.source=/lib64 
  become: yes
  when: ansible_os_family == "RedHat" and hpe3par_plugin_version != installed_version.stdout
 
- name: 3par plugin - enable docker plugin
  shell: docker plugin enable hpe
  become: yes
  when: hpe3par_plugin_version != installed_version.stdout
